Add a [tool.setuptools_scm] section
WARNING  toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'

    Traceback (most recent call last):
      File "/usr/lib/python3.13/site-packages/setuptools_scm/_in
    tegration/pyproject_reading.py", line 36, in
    read_pyproject
        section = defn.get("tool", {})[tool_name]
                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
    KeyError: 'setuptools_scm'